# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseRemoteConfig'

end
